### ISSUE TITLE
Less train features after preprocessing

### ISSUE THREAD

**Issue by zjy-ucas** [google-research-datasets/tydiqa#5]
After process the tydiqa-v1.0-train.jsonl.gz with the default setting, the size of train.tfrecord is 318M instead of 1.7G as shown in the readme.
Besides, the eval result of model trained with this train set is:
{
"avg_passage_f1": 0.31634277041785736, 
"avg_passage_recall": 0.4902131008441125, 
"avg_passage_precision": 0.24037818047844128, 
"avg_minimal_f1": 0.26148920297670364, 
"avg_minimal_recall": 0.3988957075364443, "
avg_minimal_precision": 0.20042686697459713
}
maybe the default setting doesn't sample UNKNOW instance?

**Comment by chanzy3** [comment]
I also got the same size for train.tfrecord and achieved the same result like yours after running the baseline model with this default setting. Have you successfully resolved the problem?

**Comment by jhclark-google** [comment]
I'm looking into this now.

Apologies for the delay. I wasn't receiving Issue notifications as expected.

**Comment by chanzy3** [comment]
Thanks so much for the quick response, I think the issue might be that you have to set include_unknowns to 0.02 instead of default choice -1 because the original paper says to downsample unknown instances by 50 times.

**Comment by jhclark-google** [comment]
@chanzy3: Yes, I think that's the issue; looks like I neglected to copy-paste a parameter from my test command line to the README.md.

I'll update the README.md to include `--include_unknowns=0.1` for the training data (not dev).

Apologies for the error in the documentation.

**Comment by chanzy3** [comment]
@jhclark-google Shouldn't we set --include_unknowns=0.02 (1/50) as was mentioned in the baseline paper: https://arxiv.org/pdf/1901.08634.pdf?
"We downsample null instances by 50 times in order to obtain a training set that has roughly as many null instances as non-null instances"

**Comment by jhclark-google** [comment]
@chanzy3: I don't think the exact value of this should matter much, but we did use `--include_unknowns=0.1` in the final experiments. I'll update the paper to reflect this.

**Comment by chanzy3** [comment]
@jhclark-google Thanks so much! We did try using include_unknowns = 0.1 and reached the similar F1 score as mentioned in the paper:)

**Comment by jhclark-google** [comment]
Glad to hear it. Let us know if you run into anything else. Happy training. :)
