### ISSUE TITLE
Yes/No predictions issue

### ISSUE THREAD

**Issue by tomohideshibata** [google-research-datasets/tydiqa#8]
In `postproc.py`, `yes_no_answer` in `summary.predicted_label` seems to be fixed to "NONE", and `summary.answer_type_logits` are not used. The codes do not handle yes/no predictions?
https://github.com/google-research-datasets/tydiqa/blob/master/baseline/postproc.py#L161

Thanks.

**Comment by jhclark-google** [comment]
You are correct. YES/NO are not handled by the initial baseline, similar to the BERT baseline for the Natural Questions: https://github.com/google-research/language/blob/master/language/question_answering/bert_joint/run_nq.py#L1226. This is left as future work for the community. We're excited to see what folks do in this area.

**Comment by tomohideshibata** [comment]
Thanks for your explanation.
