### ISSUE TITLE
Minimal answer spans are wrong for some examples.

### ISSUE THREAD

**Issue by alibi123** [google-research-datasets/tydiqa#9]
When I try to read the data and print questions and minimal span answers, I noticed that for some examples `plaintext_start_byte` and `plaintext_end_byte` of minimal answer span are shifted by `k` symbols right. 

Example:
Question: 'Who created the series Clannad?'
Minimal span: 'rel' (it should be 'Key', but its values are shifted and it gives 'rel' part of the word 'released')
```
... Clannad(クラナド,Kuranado) is a Japanese visual novel developed by Key and released on April 28, 2004 ...
```

This is how I read the data file:
```

    with open(path_name) as input_file:
        for line in input_file:
            try:
                json_example = json.loads(line)
                if json_example['language'] not in allowed_langs:
                    continue

                plain_text = json_example['document_plaintext']
...
```

**Comment by dhgarrette** [comment]
I suspect that you're doing a slice on the Python string's characters instead of bytes.  In Python3, string indices are given in unicode characters (unlike Python2, which used bytes).  The example you gave has non-ascii characters that take up more than one byte, so the byte and character indices will not be the same:

```python
>>> plaintext = "Clannad(クラナド,Kuranado) is a Japanese visual novel developed by Key and released on"
>>> plaintext_start_byte = 71
>>> plaintext_end_byte = 74
>>> plaintext[plaintext_start_byte:plaintext_end_byte]  # Incorrect
'rel'
>>> plaintext.encode()[plaintext_start_byte:plaintext_end_byte].decode()  # Correct
'Key'
```

**Comment by alibi123** [comment]
@dhgarrette Thank you, it worked.

**Comment by tomohideshibata** [comment]
If a plaintext has an HTML tag (e.g., `</b>`), an answer span seems strange (I have checked it only for Japanese).

The following is from an example whose "example_id" is "-4305955023654558700" in `tydiqa-v1.0-dev.jsonl.gz`.

```python
>>> plaintext = "\nアニー・ウッド・ベサント（Annie Wood Besant, ベザント</b>とも表記されるが発音は「bɛsənt」, 1847年10月1日 ロンドン、クラパム.."
>>> plaintext_start_byte = 118
>>> plaintext_end_byte = 132
>>> plaintext.encode("utf-8")[plaintext_start_byte:plaintext_end_byte].decode("utf-8", errors="replace")
t」, 1847年1
```

The output should be `1847年10月1日`.
When `</b>` is deleted from the plaintext, the output will be `, 1847年10月`, which is better than the original one. But, this still includes a needless `, `.

The detag for the plaintext is missing? Thanks.

**Comment by jhclark-google** [comment]
Thanks for reporting this. This one does look like some combination of an
HTML parsing/stripping error and possible an annotation error in terms of
inexact bounds.

Have you noticed this as a pattern? Or was it just this example that you
noticed?

**Comment by tomohideshibata** [comment]
Thanks for your reply.
All the examples (less than 10 in `tydiqa-v1.0-dev.jsonl.gz`) I have noticed include a `<b>` or `</b>`  tag. (e.g., example_id: -475406398362175740)

But, in the following example (example_id: 2411700655539355000), the extracted span is OK even if the plaintext includes `</b>`. I can't find a clear pattern.

```python
>>> plaintext = "ハインケル</b>とはエルンスト・ハインケル(Ernst Heinkel)博士によって設立されたハインケル航空機製造会社(Heinkel Flugzeugwerke)を指す。ヴェルサイユ条約による航空機製造禁止が緩和された1922年にドイツ北部のロストック近郊のヴァーネミュンデ (Warnemünde) に設立された。"
>>> plaintext_start_byte = 249
>>> plaintext_end_byte = 256
>>> plaintext.encode("utf-8")[plaintext_start_byte:plaintext_end_byte].decode("utf-8", errors="replace")
1922年
```

**Comment by asahi417** [comment]
Does anyone come up with any universal approaches to fix the mismatch in the end? I'm also having issues when I extract answers from the context and as described in the above, I don't see any obvious pattern whether it fails or not.

**Comment by hashedi** [comment]
I think @tomohideshibata code works fine
